version: '3.8'

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    command: /start
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
