# Generated by Django 4.2.11 on 2024-05-07 07:10

from django.db import migrations, models
import urlshortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('alias', models.CharField(blank=True, default=urlshortener.models.generate_alias, max_length=15, unique=True)),
            ],
        ),
    ]
